### ISSUE TITLE
'ledz' was not declared in this scope

### ISSUE THREAD

**Issue by mashoudul** [jordanadania/fastled-newFlow#1]
hello, dear happy new year. dear, I have a problem,  your led code upload time error ................... exit status 1 _**'ledz' was not declared in this scope**_        this red line error      _**if(bri==0) ledz[ok] = CRGB(0,1,0);**_    what can I do And a great project like that,

i will hope happy to solution with me
dear i can run your project ?

**Comment by jordanadania** [comment]
That array name was most likely changed to grbleds, but let me double check.

**Comment by jordanadania** [comment]
I have updated all files EXCEPT audio.h and README.txt

Please let me know if this resolves your issues!

Thanks!

**Comment by mashoudul** [comment]
now under problem, I use **FastLED-3.003.003** **FastLED-3.1.0** and your link FastLED  problem **_'ledz' was not declared in this scope_**

what number I can use FASTLED 

**_Flow:13:21: fatal error: FastLED.h: No such file or directory

 #include "FastLED.h"

                     ^

compilation terminated.

exit status 1
FastLED.h: No such file or directory_**

**Comment by jordanadania** [comment]
I have updated the README file.  Hopefully it contains all the information you need to get started! Let me know if you have any other issues!
