### ISSUE TITLE
NUM_LEDS' was not declared 

### ISSUE THREAD

**Issue by mashoudul** [jordanadania/fastled-newFlow#2]
what happened I don't **same error**  many time try what can i do i don't know. sorry again question 

**'NUM_LEDS' was not declared in this scope**

In file included from C:\Users\sickboy\Pictures\fastled-newFlow-master\Flow\Flow.ino:13:0:
C:\Users\sickboy\Documents\Arduino\libraries\FastLED\src/FastLED.h:14:21: note: #pragma message: FastLED version 3.004.000
 #    pragma message "FastLED version 3.004.000"
                     ^
In file included from C:\Users\sickboy\Documents\Arduino\libraries\FastLED\src/FastLED.h:65:0,
                 from C:\Users\sickboy\Pictures\fastled-newFlow-master\Flow\Flow.ino:13:
C:\Users\sickboy\Documents\Arduino\libraries\FastLED\src/fastspi.h:135:23: note: #pragma message: No hardware SPI pins defined.  All SPI access will default to bitbanged output
 #      pragma message "No hardware SPI pins defined.  All SPI access will default to bitbanged output"
                       ^
Flow:41:11: error: 'NUM_LEDS' was not declared in this scope
 CRGB leds[NUM_LEDS];  // Main Array
           ^
In file included from C:\Users\sickboy\Pictures\fastled-newFlow-master\Flow\Flow.ino:49:0:
sketch\Pattern.h: In function 'void fadeWhites(uint8_t)':
Pattern.h:2:18: error: 'NUM_LEDS' was not declared in this scope
   for(int i=1; i<NUM_LEDS-1; ++i)                                 
                  ^
Pattern.h:3:9: error: 'leds' was not declared in this scope
     if((leds[i].r==leds[i].g && leds[i].g==leds[i].b           // if LED is white AND
         ^
sketch\Pattern.h: In function 'void freshWhites()':
Pattern.h:13:18: error: 'NUM_LEDS' was not declared in this scope
   for(int i=0; i<NUM_LEDS; ++i)
                  ^
Pattern.h:14:8: error: 'leds' was not declared in this scope
     if(leds[i].r==leds[i].g && leds[i].g==leds[i].b)
        ^
sketch\Pattern.h: In function 'void goGray()':
Pattern.h:18:23: error: 'NUM_LEDS' was not declared in this scope
   for(uint16_t i=0; i<NUM_LEDS; ++i)
                       ^

**Comment by jordanadania** [comment]
I have updated Flow.ino -- this should solve this issue.

**Comment by mashoudul** [comment]
'Audio' was not declared in this scope

Now this problem 

Can u use fastled ver.
Esp bord manager ver.
And Arduino ide ver.

**Comment by jordanadania** [comment]
Lolol

**Comment by jordanadania** [comment]
Im so sorry for all these mistakes.

**Comment by jordanadania** [comment]
I have updated pattern.h to solve your issue.

**Comment by mashoudul** [comment]
'rgbRate' was not declared in this scope

171 line pattern.h

**Comment by jordanadania** [comment]
should be solved now.

**Comment by mashoudul** [comment]
Dear many other **was not declared in this scope**

you are a very responsible person I wanted to don't disturb you.

My self how can I solved it.
Because I like 😍 your project,

**Comment by jordanadania** [comment]
solved

**Comment by jordanadania** [comment]
sorry this was so difficult!
