### ISSUE TITLE
Electronics Diagram

### ISSUE THREAD

**Issue by burntpcb** [jordanadania/fastled-newFlow#3]
What is the electronics diagram for this project? What pins on the MSGEQ7 correspond to the ESP? What pins do the neopixels connect to? Thanks

**Comment by jordanadania** [comment]
the neopixels pin is in Flow.ino on line 27. you can make it whatever you want.

the audio pin is in Audio.h on lines 7,8,9

**Comment by burntpcb** [comment]
Gonna be honest, I am really new to electronics and whenever I plug in the neopixel the pcb lights on fire (hence the name). I have the MSGEQ7 and ESP wired together, and I connect the power of neopixel to Vin, ground to ground, and pin to D2, each time the circuit lights up. Any advice? Thanks again for the help

**Comment by jordanadania** [comment]
it lights on fire? I don't understand.

**Comment by burntpcb** [comment]
the ESP8266 shorts and lights on fire with the current layout, I am not sure what I am doing wrong

**Comment by jordanadania** [comment]
you see flames? that's not a me problem
